local map = vim.keymap.set

map("n", "<Esc>", "<cmd>nohlsearch<CR>", { desc = "Clear search highlighting" })

map("n", "<leader>fd", function()
    Snacks.picker.files()
end, { desc = "Find files" })
map("n", "<leader>fg", function()
    Snacks.picker.grep()
end, { desc = "Find text" })
map("n", "<leader>fb", function()
    Snacks.picker.buffers()
end, { desc = "Find buffers" })
map("n", "<leader>fh", function()
    Snacks.picker.help()
end, { desc = "Find help" })
map("n", "<leader>fr", function()
    Snacks.picker.recent()
end, { desc = "Find recent files" })

map("n", "<leader>gi", function()
    Snacks.picker.gh_issue()
end, { desc = "GitHub issues (open)" })
map("n", "<leader>gI", function()
    Snacks.picker.gh_issue({ state = "all" })
end, { desc = "GitHub issues (all)" })
map("n", "<leader>gp", function()
    Snacks.picker.gh_pr()
end, { desc = "GitHub pull requests (open)" })
map("n", "<leader>gP", function()
    Snacks.picker.gh_pr({ state = "all" })
end, { desc = "GitHub pull requests (all)" })
